import type { LucideIcon, LucideProps } from 'lucide-react';
import {
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Ban,
  BookOpen,
  Bot,
  Box,
  Brain,
  ChartLine,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleHelp,
  Clock,
  Cloud,
  CloudUpload,
  Code,
  Copy,
  CornerUpRight,
  Cpu,
  Download,
  Ellipsis,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileAudio,
  FileCode,
  FileImage,
  FilePen,
  FilePlus2,
  FileQuestion,
  FileSpreadsheet,
  FileText,
  FileUp,
  FileVideo,
  Film,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderTree,
  GitBranch,
  Globe,
  Hash,
  History,
  House,
  Image,
  Info,
  KeyRound,
  Layers,
  Lightbulb,
  Link,
  LoaderCircle,
  Lock,
  LogOut,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareDot,
  MessagesSquare,
  Mic,
  Minimize2,
  Moon,
  Network,
  Paperclip,
  Pen,
  Pin,
  Play,
  Plus,
  Puzzle,
  QrCode,
  RadioTower,
  RotateCw,
  Scissors,
  Search,
  Send,
  Shield,
  Signal,
  SlidersHorizontal,
  Sprout,
  Square,
  SquareDashed,
  SquarePen,
  Sun,
  Terminal,
  ToggleLeft,
  ToggleRight,
  Trash2,
  TriangleAlert,
  Volume2,
  WandSparkles,
  Wifi,
  Wrench,
  X,
  Zap,
} from 'lucide-react';

/**
 * Map of Font Awesome class names (still used as data throughout the app:
 * VIEW_META, PERMISSION_META, SLASH_COMMANDS, tool/channel/mock icon strings…)
 * to their lucide-react equivalent. QwenPaw's console uses lucide, so this
 * keeps every icon on the same visual system.
 */
const ICONS: Record<string, LucideIcon> = {
  'fa-file-lines': FileText,
  'fa-chevron-right': ChevronRight,
  'fa-plus': Plus,
  'fa-chevron-down': ChevronDown,
  'fa-magnifying-glass': Search,
  'fa-search': Search,
  'fa-clock': Clock,
  'fa-folder-tree': FolderTree,
  'fa-folder': Folder,
  'fa-folder-open': FolderOpen,
  'fa-folder-plus': FolderPlus,
  'fa-brain': Brain,
  'fa-eye': Eye,
  'fa-eye-slash': EyeOff,
  'fa-pen-to-square': SquarePen,
  'fa-pen': Pen,
  'fa-globe': Globe,
  'fa-terminal': Terminal,
  'fa-microchip': Cpu,
  'fa-trash': Trash2,
  'fa-trash-can': Trash2,
  'fa-bolt': Zap,
  'fa-key': KeyRound,
  'fa-sliders': SlidersHorizontal,
  'fa-sliders-h': SlidersHorizontal,
  'fa-circle-info': Info,
  'fa-info-circle': Info,
  'fa-file-circle-plus': FilePlus2,
  'fa-seedling': Sprout,
  'fa-circle-question': CircleHelp,
  'fa-thumbtack': Pin,
  'fa-book': BookOpen,
  'fa-robot': Bot,
  'fa-check': Check,
  'fa-image': Image,
  'fa-file-arrow-up': FileUp,
  'fa-file-pen': FilePen,
  'fa-spinner': LoaderCircle,
  'fa-arrow-left': ArrowLeft,
  'fa-triangle-exclamation': TriangleAlert,
  'fa-puzzle-piece': Puzzle,
  'fa-diagram-project': Network,
  'fa-toggle-off': ToggleLeft,
  'fa-toggle-on': ToggleRight,
  'fa-tower-broadcast': RadioTower,
  'fa-rotate-right': RotateCw,
  'fa-refresh': RotateCw,
  'fa-file-pdf': FileText,
  'fa-file-code': FileCode,
  'fa-file-image': FileImage,
  'fa-file-video': FileVideo,
  'fa-file-audio': FileAudio,
  'fa-file-csv': FileSpreadsheet,
  'fa-file-word': FileText,
  'fa-file-alt': FileText,
  'fa-file': File,
  'fa-message': MessageSquare,
  'fa-comment': MessageSquare,
  'fa-comment-dots': MessageSquareDot,
  'fa-download': Download,
  'fa-house': House,
  'fa-wrench': Wrench,
  'fa-arrow-turn-up': CornerUpRight,
  'fa-paper-plane': Send,
  'fa-copy': Copy,
  'fa-shield-halved': Shield,
  'fa-arrow-right-arrow-left': ArrowLeftRight,
  'fa-microphone': Mic,
  'fa-arrow-right': ArrowRight,
  'fa-code-branch': GitBranch,
  'fa-ban': Ban,
  'fa-vector-square': SquareDashed,
  'fa-play': Play,
  'fa-lock': Lock,
  'fa-volume-high': Volume2,
  'fa-volume-up': Volume2,
  'fa-cube': Box,
  'fa-qrcode': QrCode,
  'fa-film': Film,
  'fa-lightbulb': Lightbulb,
  'fa-clock-rotate-left': History,
  'fa-bars': Menu,
  'fa-code': Code,
  'fa-chart-line': ChartLine,
  'fa-cloud-arrow-up': CloudUpload,
  'fa-stop': Square,
  'fa-magic': WandSparkles,
  'fa-paperclip': Paperclip,
  'fa-moon': Moon,
  'fa-signal': Signal,
  'fa-file-circle-question': FileQuestion,
  'fa-xmark': X,
  'fa-times': X,
  'fa-layer-group': Layers,
  'fa-cloud': Cloud,
  'fa-compress': Minimize2,
  'fa-eraser': Eraser,
  'fa-sign-out-alt': LogOut,
  'fa-sun': Sun,
  'fa-ellipsis': Ellipsis,
  'fa-link': Link,
  'fa-up-right-from-square': ExternalLink,
  'fa-circle': Circle,
  'fa-scissors': Scissors,
  // Channel / brand icons that may arrive from the backend.
  'fa-wifi': Wifi,
  'fa-weixin': MessageCircle,
  'fa-wechat': MessageCircle,
  'fa-telegram': Send,
  'fa-slack': Hash,
  'fa-discord': MessagesSquare,
  'fa-message-dots': MessageSquareDot,
};

type AppIconProps = Omit<LucideProps, 'ref'> & {
  /** Explicit icon name; when omitted it is read from the `fa-*` class. */
  name?: string;
};

/**
 * Renders an icon for a Font Awesome class name, backed by lucide-react.
 * Sizes at `1em` by default so the existing `text-xs`/`text-sm` classes and
 * text colour keep working exactly like the old `<i class="fas …" />`.
 */
export function AppIcon({ name, className = '', size = '1em', strokeWidth = 2, ...rest }: AppIconProps) {
  const tokens = className.split(/\s+/).filter(Boolean);
  const faName = name ?? tokens.find((t) => t.startsWith('fa-') && t !== 'fa-spin');
  const Cmp = (faName && ICONS[faName]) || CircleHelp;
  const spin = tokens.includes('fa-spin');
  const cleaned = tokens
    .filter((t) => t !== 'fas' && t !== 'far' && t !== 'fab' && t !== 'fa-spin' && !t.startsWith('fa-'))
    .join(' ');

  return (
    <Cmp
      size={size}
      strokeWidth={strokeWidth}
      aria-hidden="true"
      focusable="false"
      className={spin ? `${cleaned} animate-spin`.trim() || undefined : cleaned || undefined}
      {...rest}
    />
  );
}
